### ISSUE TITLE
missing intellisense/code hint

### ISSUE THREAD

**Issue by Lichtjaeger** [GarthDB/Brackets-Stylus#14]
I missing some intellisense like it would be in the css editor.

**Comment by dmitrykiselyov** [comment]
Like Code hints, Quick Docs, Live Preview ... ?
Brackets don't have native support for Stylus. You can [vote](https://trello.com/c/UgaiJ8Bi) :white_check_mark: for that :smile:

**Comment by Lichtjaeger** [comment]
Thanks. Have voted.

**Comment by sprintr** [comment]
I wrote an [extension](https://github.com/sprintr/brackets-stylus-code-hints) for it.

**Comment by dmitrykiselyov** [comment]
@sprintr :+1:
